org: kauelima21
service: kaueleal-api

plugins:
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: dev
  architecture: arm64
  memorySize: 512
  timeout: 10
  logRetentionInDays: 7
  environment:
    MESSAGES_TABLE: !Ref MessagesTable

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  messages:
    name: messages_${self:provider.stage}
    handler: source/functions/messages.postHandler
    events:
      - http:
          path: /messages
          method: post
          cors: true
    iamRoleStatementsName: messages_${self:provider.stage}_role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt MessagesTable.Arn

  processStreams:
    name: process_streams_${self:provider.stage}
    handler: source/functions/processStreams.handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt MessagesTable.StreamArn
          batchSize: 5
          maximumRetryAttempts: 2
          destinations:
            onFailure:
              type: sqs
              arn: !GetAtt DynamDBStreamsDQL.Arn
    iamRoleStatementsName: process_streams_${self:provider.stage}_role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: !GetAtt DynamDBStreamsDQL.Arn
      - Effect: Allow
        Action:
          - ses:SendEmail
        Resource: '*'

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    DynamDBStreamsDQL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: DynamDBStreamsDQL
        MessageRetentionPeriod: 1209600 # 14 days

    ApiGatewayUsagePlan:
      Type: AWS::ApiGateway::UsagePlan
      Properties:
        Throttle:
          BurstLimit: 10
          RateLimit: 5
        UsagePlanName: "DefaultLimit"
        ApiStages:
          - ApiId: !Ref ApiGatewayRestApi
            Stage: ${self:provider.stage}
